CapstoneFinal/Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string TaskName { get; set; }
        public string Description { get; set; }
        public System.DateTime Duedate { get; set; }
        public string UserEmail { get; set; }
        public int TaskID { get; set; }
    
        public virtual User User { get; set; }
    }
}

CapstoneFinal/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CapstoneFinal.Models
{
    public class TaskViewModel
    {
        public string Email { get; set; }

        public List<Task> TaskList { get; set; }
    }
}

CapstoneFinal/Models/TasksDBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskListEntities : DbContext
    {
        public TaskListEntities()
            : base("name=TaskListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}

CapstoneFinal/Models/TasksDBModel.Designer.cs
// T4 code generation is enabled for model 'c:\users\maggie\source\repos\CapstoneFinal\CapstoneFinal\Models\TasksDBModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

CapstoneFinal/Models/TasksDBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

CapstoneFinal/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public string Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

CapstoneFinal/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CapstoneFinal.Models
{
    public class UserViewModel
    {
        public string Name { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

    }
}

CapstoneFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CapstoneFinal/Controllers/TasksController.cs
using CapstoneFinal.DAO;
using CapstoneFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneFinal.Controllers
{
    public class TasksController : Controller
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Search(TaskViewModel model)
        {
            //todo
            model.TaskList = TaskDao.GetTasksByEmail(model.Email);

            return View(model);
        }

        public ActionResult UserTasks(TaskViewModel user)
        {
            user.TaskList = TaskDao.GetTasksByEmail(user.Email);
            return View(user);
        }
    }


}

CapstoneFinal/Controllers/UsersController.cs
using CapstoneFinal.DAO;
using CapstoneFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneFinal.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register(User user)
        {
            TaskListEntities db = new TaskListEntities();
            if (ModelState.IsValid)
            {
                try
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    ViewBag.Message = $"Welcome {user.Name}! ";
                    return View(user);
                }
                catch (Exception e)
                {
                    ViewBag.Message = $"Error: {e.Message}";
                    return View(user);
                }
                finally
                {
                    View ("/Tasks/UserTasks");
                    ViewBag.Message = $"Welcome {user.Name}! ";
                }
            }
            ViewBag.Message = $"Welcome {user.Name}! ";
            return View();
        }

        
        public ActionResult Login(User model)
        {
            TaskListEntities db = new TaskListEntities();
            var userRecord = db.Users.FirstOrDefault(u => u.Email == model.Email);

            if (model == null)
            {
                ViewBag.Message = $"Error {model.Email} was not recognized";
            }
            else
            {
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View();
        }
    }
}

CapstoneFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CapstoneFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CapstoneFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p class="lead">Welcome to the: </p>
    <h1>Task Manager Application</h1>
 </div>

<div class="row">
    <div class="col-md-4">
        <p><a class="btn btn-default" href="/Users/Login">Login &raquo;</a></p>
    </div>
    <div class="col-md-4">

        <p><a class="btn btn-default" href="/Users/Register">Register &raquo;</a></p>
    </div>
    <div class="col-md-4">

        <p><a class="btn btn-default" href="/Tasks/Search">Search &raquo;</a></p>
    </div>
</div>

CapstoneFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Task Manager Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Task Manager Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Search", "Search", "Tasks")</li>
                    <li>@Html.ActionLink("Log In", "Login", "Users")</li>
                    <li>@Html.ActionLink("Register", "Register", "Users")</li>
                    <li>@Html.ActionLink("Log Out", "Logout", "Users")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Task Manager Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CapstoneFinal/Views/Tasks/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

CapstoneFinal/Views/Tasks/Search.cshtml
@model CapstoneFinal.Models.TaskViewModel
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
<p>Enter an email to view tasks assigned to tha user: </p>

@using (Html.BeginForm("Search", "Tasks", FormMethod.Post))
{
<div>
    Email: @Html.TextBoxFor(model => model.Email, new { id = "email", maxlength = 255 })
    <button type="submit" class="btn">Seach</button>
</div>
  }


@if (Model?.TaskList != null)
{
    <br />
    <table class="table table-bordered table-responsive">
        <tr>
            <th>Task Name:</th>
            <th>Task Description:</th>
            <th>Task Due Date:</th>
        </tr>
        @foreach (var task in Model.TaskList)
        {
            <tr>
                <td> @task.TaskName </td>
                <td>@task.Description </td>
                <td>@task.Duedate </td>
            </tr>
        }
    </table>
}
else
{
    <p class="text-danger"><em>Nothing to display. Please try another email address </em></p>
}

CapstoneFinal/Views/Tasks/UserTasks.cshtml
@{
    ViewBag.Title = "UserTasks";
}

<h2>Your Tasks: </h2>
<p>@ViewBag.Message</p>

@if (Model?.TaskList != null)
{
    <br />
    <table class="table table-bordered table-responsive">
        <tr>
            <th>Task Name:</th>
            <th>Task Description:</th>
            <th>Task Due Date:</th>
        </tr>
        @foreach (var task in Model.TaskList)
        {
            <tr>
                <td> @task.TaskName </td>
                <td>@task.Description </td>
                <td>@task.Duedate </td>
            </tr>
        }
    </table>
}
else
{
    <p class="text-danger"><em>No tasks to display yet </em></p>
}

CapstoneFinal/Views/Users/Login.cshtml
@model CapstoneFinal.Models.User
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm("UserTasks", "Tasks", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User Login</h4>
       <p> @ViewBag.Message </p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn">Log In</button>
            </div>
        </div>
    </div>
}

CapstoneFinal/Views/Users/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>
<p>You have been successfully logged out!</p>

Back to home <a href="/Home/Index">Home</a>

CapstoneFinal/Views/Users/Register.cshtml
@model CapstoneFinal.Models.User

@{
    ViewBag.Title = "Register New User";
}

<h2>Register</h2>

@using (Html.BeginForm("UserTasks", "Tasks", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn">Register</button>
            </div>
        </div>
    </div>
}